---
settings:
  name: Amazon S3 storage
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  release_notes_autogen:
    release_notes_repo: console-relnotes
  rss_page: whats-new.html
  langs: de-de,us-en,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Amazon S3-Speicherdokumente
    url: "/index.html"
  - title: Versionshinweise
    url: "/whats-new.html"
  - title: Erste Schritte
    entries:
    - title: Zeigen Sie Ihre Amazon S3-Buckets an
      url: "/task-viewing-amazon-s3.html"
  - title: S3-Buckets verwalten
    entries:
    - title: S3-Buckets hinzuf체gen
      url: "/task-add-s3-bucket.html"
    - title: S3-Bucket-Einstellungen 채ndern
      url: "/task-change-s3-bucket-settings.html"
    - title: NetApp Datendienste mit S3-Buckets nutzen
      url: "/task-s3-enable-data-services.html"
  - title: Wissen und Unterst체tzung
    entries:
    - title: F체r Support registrieren
      url: "/task-support-registration.html"
    - title: Hilfe erhalten
      url: "/task-get-help.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: Storage Management
  repo: storage-management-family
